### ISSUE TITLE
funlocks

### ISSUE THREAD

**Issue by kota-shiokara** [kota-shiokara/MyGameOfLife#4]
funlocksのためにやること
- [x] androidでの位置情報取得に関して調べる
- [x] androidでのビーコンと通信に関して調べる

- [x] JSでの位置情報取得に関して調べる
- [x] JSでのビーコンと通信に関して調べる

- [x] 実機を用意する

**Comment by Atria64** [comment]
がんばれ

**Comment by kota-shiokara** [comment]
実機の受け渡し終わったので「急ぎ」ラベルを外す

**Comment by kota-shiokara** [comment]
- [ ] androidのBluetooth端末検知の知見を得る(MainActivityのみの軽いアプリ作ってみる？)

**Comment by kota-shiokara** [comment]
- [ ] 木曜にメンバーに「はじめてのAndroid」を貸す

**Comment by kota-shiokara** [comment]
以降team05での活動とする
